services:
  app:
    image: zrdax/express-docker-pipeline:latest
    container_name: express-app
    ports:
      - 8080:8080

  watchtower:
    image: containrrr/watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - WATCHTOWER_POLL_INTERVAL=60
